preload = ~/.config/hypr/wallpaper/background-kawaiii.png

wallpaper = , ~/.config/hypr/wallpaper/background-kawaiii.png
wallpaper = , ~/.config/hypr/wallpaper/background-purple.jpg
wallpaper = , ~/.config/hypr/wallpaper/background-arch.png

IPC = off
