
# Yazi
windowrule = float, title:^yazi$
windowrule = size 1600 900, title:^yazi$
windowrule = center, title:^yazi$

# Wiremix
windowrule = float, title:^wiremix$
windowrule = size 1200 500, title:^wiremix$
windowrule = center, title:^wiremix$
